FindInvest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('reset_password', views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='reset_password'),
    path('reset_password_send', views.PasswordResetDoneView.as_view(template_name='registration/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password_complete', views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name="index"),
    path('accueil', accueil, name="accueil"),

    #  crud post
    path('delete_post/<str:pk>', delete_post, name='delete_post'),
    path('update_post/<str:pk>', update_post, name='update_post'),
    path('create_post', create_post, name='create_post'),
    path('list_projects', list_projects, name='list_projects'),
    path('mes_projets/<str:id_e>', mes_projets, name='mes_projets'),


    # chat 
    path('<str:room>/', room, name="room"),
    path('send', send, name='send'),
    path('getMessages/<str:room>/', getMessages, name='getMessages'),
    path('createRoom/<str:u1>/<str:u2>/<str:title>', createRoom, name='createRoom'),

    # comment post
    path('CommentPost', CommentPost, name='CommentPost'),
    path('getComments', getComments, name='getComments'),

    # favoris
    path('favoris/<str:id_u>', favoris, name="favoris"),
    path('createFavoris', createFavoris, name="createFavoris"),
    path('getFavoris', getFavoris, name='getFavoris'),

    # marquer investi
    path('markPost', markPost, name='markPost'),

]

posts/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
from users.models import Etudiant, Investisseur
import os
from PIL import Image
from django.utils import timezone

# creation de la classe Projet

class Projet(models.Model):
    INVESTI = [
        ('Oui', 'Oui'),
        ('Non', 'Non'),
    ]
    CATHEGORIES = [
        ('INFORMATIQUE','INFORMATIQUE'),
        ('AGRICULTURE','AGRICULTURE'),
        ('ELEVAGE','ELEVAGE'),
        ('SANTE','SANTE'),
        ('AUTRES','AUTRES')
    ]

    title = models.CharField('Titre du Projet', max_length=200)
    categorie = models.CharField('categorie projet', max_length=200, choices=CATHEGORIES, default='categorie')
    media = models.FileField(upload_to='documents/post_doc/', blank=True)
    image = models.ImageField(upload_to='image/post_image/', default='post.jpg', blank=True)
    investi = models.CharField(choices=INVESTI, default='Non', max_length=10, blank=True)

    description = models.TextField(max_length=500)
    # un projet ne concerne qu'un etudiant
    etudiant = models.ForeignKey(Etudiant, on_delete=models.CASCADE, related_name='projet')
    date_post = models.DateTimeField('date_post',auto_now_add=True, blank=True)

    def __str__(self):
        return  f'{self.title} par {self.etudiant.user.last_name}'
    class Meta:
        ordering = ['-date_post']


# models pour le Chat

class Room(models.Model):
    name = models.CharField(max_length=100)
    # inv = models.CharField(max_length=100)
    # etu = models.CharField(max_length=1000)
    inv = models.ForeignKey(Investisseur, on_delete=models.CASCADE, related_name="room")
    etu = models.ForeignKey(Etudiant, on_delete=models.CASCADE, related_name='room')
    def __str__(self):
        return self.name


class Message(models.Model):
    value = models.CharField(max_length=1000000)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    # room = models.CharField(max_length=100)
    user = models.CharField(max_length=100)
    # user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='message')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='message')

    def __str__(self):
        return f'Msg de {self.user} le {self.date}'




# models pour le système de commentaires

class Commentaire(models.Model):
    projet = models.ForeignKey(Projet, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, models.CASCADE)

    def __str__(self):
        return f'Commentaire de {self.user} pour {self.projet.title}'
    

class ComMessage(models.Model):
    commentaire = models.ForeignKey(Commentaire, on_delete=models.CASCADE, related_name="contenus")
    auteur = models.CharField(max_length=100)
    id_projet = models.CharField(max_length=100, null=True)
    corps = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Contenue du {self.auteur} le {self.date_added}'
    class Meta:
        ordering = ['-date_added']


class Reponse(models.Model):
    commentaire = models.ForeignKey(Commentaire, on_delete=models.CASCADE, related_name='reponses')
    auteur = models.ForeignKey(User, models.CASCADE)
    corps = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Reponse de {self.auteur} au commentaire de {self.commentaire.auteur}'
    class Meta:
        ordering = ['-date_added']




# models l'ajout d'un projet en favoris

class Favoris(models.Model):
    projet = models.ForeignKey(Projet, on_delete=models.CASCADE, related_name='favoris')
    user = models.ForeignKey(User, models.CASCADE)
    nomFav = models.CharField(max_length=100)
    id_proj = models.CharField(max_length=100, null=True)
    id_usr = models.CharField(max_length=100, null=True)

posts/forms.py
from dataclasses import field
from pyexpat import model
from django import forms
from .models import Projet, Commentaire, Reponse


class ProjetForm(forms.ModelForm):
	class Meta():
		model = Projet
		fields = [
			'title',
			'categorie',
			'media',
			'image',
			'investi',
			'description',
			'etudiant',
            
		]

# class ComForm(forms.ModelForm):
# 	class Meta():
# 		model = Commentaire
# 		fields = ['corps',]
# 		labels = {'corps': 'Commentaires'}
# 		widgets = {
# 			'corps': forms.Textarea(attrs={
# 				'class':'form-control',
# 				'rows':4,
# 				'cols':70,
# 				'placeholder':'Votre commentaire'
# 			})
# 		}

class RepForm(forms.ModelForm):
	class Meta():
		model = Reponse
		fields = ['corps',]
		labels = {'corps': 'Reponses'}
		widgets = {
			'corps': forms.Textarea(attrs={
				'class':'form-control',
				'rows':2,
				'cols':10,
				'placeholder':'Votre réponse'
			})
		}

posts/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from users.models import *
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .forms import ProjetForm, RepForm
from .models import Projet, Room, Message, Commentaire, ComMessage, Reponse, Favoris

# Create your views here.



# page d'accueil (1)

def index(request):
    return render(request, 'posts/index.html')


# page d'accueil (2) des publications

@login_required(login_url='connexion')
def accueil(request):
    # crer un projet
    err_create_post =""
    create_post_form = ProjetForm()
    postList = Projet.objects.all()
    postListUnique = []
    pListCat = []
    for p in postList:
        if p.categorie not in pListCat:
            postListUnique.append(p)
            pListCat.append(p.categorie)

    # chat
    roomList = Room.objects.all()
    userList = User.objects.all()
    
    if request.method == 'POST':
        if request.POST.get('form_type') == 'create_form':
            create_post_form = ProjetForm(request.POST, request.FILES)
            if create_post_form.is_valid():
                projet = create_post_form.save()
                projet.save()
                return HttpResponseRedirect('accueil')
            else:
                err_create_post = create_post_form.errors
    
    # comments
    # usrNameList = []
    # usrPicList = []
    # for u in userList:
    #     usrNameList.append(u.username)
    #     if Etudiant.objects.filter(user=u).exists():
    #         usrPicList.append(Etudiant.objects.get(user=u).photoProfil.url)
    #     elif Investisseur.objects.filter(user=u).exists():
    #         usrPicList.append(Investisseur.objects.get(user=u).photoProfil.url)


    # favorite
    favList = Favoris.objects.all()

    context = {
        # creer un projet
        'create_post_form':create_post_form,
        'err_create_post':err_create_post,
        'postList':postList,
        'postListUnique':postListUnique,

        # chat
        'roomList':roomList,
        'userList':userList,
        
        # comments
        # 'usrNameList':usrNameList,
        # 'usrPicList':usrPicList,

        # favorite
        'favList':favList,
    }
    return render(request, 'posts/accueil.html', context)




# ==================== CRUD POST ======================


# create a post

def create_post(request):
    err =""
    projet_form = ProjetForm()
    if request.method == 'POST':
        projet_form = ProjetForm(request.POST, request.FILES)
        if projet_form.is_valid():
            projet = projet_form.save()
            projet.save()
            return HttpResponseRedirect('list_projects')
        else:
            err = projet.errors
    context = {'projet_form':projet_form, 'err':err,}
    return render(request, 'posts/create_post.html', context)


# list of posts

def list_projects(request):
    postList = Projet.objects.all()
    
    context = {'postList':postList}
    return render(request, 'posts/list_projects.html', context)


# update de project
@login_required(login_url='connexion')
def update_post(request, pk):

    publied = False
    err = ""

    projet = Projet.objects.get(id=pk)

    projet_form = ProjetForm(instance=projet)

    if request.method == 'POST':

        projet_form = ProjetForm(request.POST, request.FILES, instance=projet)

        if projet_form.is_valid():
            projet_form.save()
            publied = True
            return HttpResponseRedirect('../accueil')

        else:
            err = projet_form.errors

    context = {
        'err': err,
        'projet':projet,
        'projet_form': projet_form,
        'publied': publied
    }

    return render(request, 'posts/update_post.html', context)


# delete de project

@login_required(login_url='connexion')
def delete_post(request, pk):
    
    projet_del = Projet.objects.get(id=pk)

    # if request.method == 'POST':
    projet_del.delete()
    return HttpResponseRedirect('../accueil')


# mes projets
def mes_projets(request, id_e):
    postList = Projet.objects.all()
    postListUnique = []
    pListCat = []
    for p in postList:
        if p.categorie not in pListCat:
            postListUnique.append(p)
            pListCat.append(p.categorie)

    etu = Etudiant.objects.get(id=id_e)
    listProjet = Projet.objects.filter(etudiant=etu)
    usr = User.objects.get(id=etu.user.id)
    context = {
        'listProjet':listProjet,
        'usr':usr,

        'postList':postList,
        'postListUnique':postListUnique,
    }
    return render(request, 'posts/mes_projets.html', context)





# ======================== CHAT ==========================

# page de chat
def room(request, room):
    room_details = ''
    username = request.GET.get('username')
    # room_details = Room.objects.get(name=room)
    room_details = "no room"
    roomList = Room.objects.all()
    userList = User.objects.all()
    for r in roomList:
        if r.name == room:
            room_details = r
    
    # liste des username
    usernameInvList = []
    usernameEtuList = []
    for inv in Investisseur.objects.all():
        usernameInvList.append(inv.user.username)
    for etu in Etudiant.objects.all():
        usernameEtuList.append(etu.user.username)
    
    context = {
        'username': username,
        'room': room,
        'room_details': room_details,
        'roomList':roomList,
        'userList':userList,
        'usernameInvList':usernameInvList,
        'usernameEtuList':usernameEtuList,
    }
    return render(request, 'posts/room.html', context)



# # creer nouveau slaon de chat
def createRoom(request, u1, u2, title):
    inv = Investisseur.objects.get(id=u1)
    etu = Etudiant.objects.get(id=u2)
    # room = title
    # room = Room.objects.filter(name=title)
    # room = ""
    # for roo in Room.objects.all():
    #     if roo.name == title:
    #         room = roo
    if Room.objects.filter(name=title).exists():
        return redirect("/"+title+"/?username="+inv.user.username)
    else:
        new_room = Room.objects.create(name=title, inv=inv, etu=etu)
        new_room.save()
        return redirect("/"+title+"/?username="+inv.user.username)


# envoyer un message
def send(request):
    # récupérer les données du formulaire
    message = request.POST['message']
    username = request.POST['username']
    room_id = request.POST['room_id']

    # retouver les objets correspondants
    value = message
    room = Room.objects.get(id=room_id)
    user = User.objects.get(username=username)

    new_message = Message.objects.create(value=value, user=user.username, room=room)
    new_message.save()
    return HttpResponse('Message sent successfully')


# récupérer la liste des message d'un salon
def getMessages(request, room):
    room_details = Room.objects.get(name=room)
    photoInv = room_details.inv.photoProfil.url
    photoEtu = room_details.etu.photoProfil.url
    # photo = ""
    # inv = ""
    # for u in User.objects.all():
    #     if room_details.inv.user.id == u.id:
    #         # inv = Investisseur.objects.get(id=u.investisseur.id)
    #         for i in Investisseur.objects.all():
    #             if i.user.id == u.id:
    #                 inv = i
    #                 photo = inv.photoProfil.url
    messages = Message.objects.filter(room=room_details.id)
    context = {
        "messages":list(messages.values()), 
        'photoInv':photoInv, 
        'photoEtu':photoEtu
    }
    return JsonResponse(context)





# ========================== COMMENTS =====================



# commenter un projet

def CommentPost(request):
    proj = request.POST['projet']
    aut = request.POST['auteur']
    corps = request.POST['corps']

    projet = Projet.objects.get(id=proj)
    user = User.objects.get(id=aut)

    # créer un nouveau commentaire
    new_comment = Commentaire.objects.create(projet=projet, user=user)
    new_comment.save()

    # céer un nouveau message
    new_comMsg = ComMessage.objects.create(commentaire=new_comment, auteur=new_comment.user.username, id_projet=new_comment.projet.id, corps=corps)
    new_comMsg.save()

    return HttpResponse('Comment sent successfully')

def getComments(request):
    comments = ComMessage.objects.all()
    context = {
        "comments":list(comments.values()),
    }
    return JsonResponse(context)




# ====================== FAVORIS =======================

def createFavoris(request):
    proj = request.POST['projet']
    aut = request.POST['auteur']

    projet = Projet.objects.get(id=proj)
    user = User.objects.get(id=aut)
    nomFav = proj+" "+aut
    id_proj = proj
    id_usr = aut

    # créer un nouveau favoris
    if Favoris.objects.filter(nomFav=nomFav).exists():
        Favoris.objects.get(nomFav=nomFav).delete()
        return HttpResponse('Removed in Favoris list successfully')
    else:
        new_favoris = Favoris.objects.create(projet=projet, user=user, nomFav=nomFav, id_proj=id_proj, id_usr=id_usr)
        new_favoris.save()
    return HttpResponse('Added in Favoris list successfully')


def favoris(request, id_u):
    postList = Projet.objects.all()
    postListUnique = []
    pListCat = []
    for p in postList:
        if p.categorie not in pListCat:
            postListUnique.append(p)
            pListCat.append(p.categorie)


    usr = User.objects.get(id=id_u)
    projetList = Projet.objects.all()
    favList = Favoris.objects.filter(user=usr)

    listProjet = []
    for fav in favList:
        listProjet.append(fav.projet)
    nbFav = len(listProjet)
    context = {
        'listProjet':listProjet,
        'nbFav':nbFav,
        'usr':usr,

        'postList':postList,
        'postListUnique':postListUnique,
    }
    return render(request, 'posts/favoris.html', context)


def getFavoris(request):
    favoriss = Favoris.objects.all()
    context = {'favoriss':list(favoriss.values())}
    return JsonResponse(context)

templates/posts/comment.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" id="com">
    {% csrf_token %}
    <div style="width: 300px; margin: 100px;">
        {{ comment.title }}
            {{errors}}
    <input type="submit" class="btn btn-primary" value="commenter">
    </div>
    <br>

    {% for comment in comments %}
        <div class="" id="container">
            <p id="title">{{ comment.title}}</p>
        </div>
        
    {% endfor %}
    
</form>

<script>
     let form = document.getElementById('com');
     
     let container = document.getElementById('container')
     form.addEventListener('submit', StopReload)
     function StopReload(e){
       e.preventDefault();
       let title = document.createElement('p');
        $.ajax({
            type: "POST",
            url: "{% url 'comments' %}",
            data: $('#com').serialize(),
            dataType: "json",

            success:function(data){
                  title.innerText = data.new_comment;
                  container.appendChild(title)
                  form.reset()
                    }
            })
   }

</script>

{% endblock %}

templates/posts/create_post.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Create a post</title>
    </head>
    <body>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{projet_form.as_p}}

            <input type="submit" value="Poster">

            {{err}}
        </form>
    </body>
</html>

templates/posts/delete_projet.html
 {% extends 'base.html' %}
 {% load static %}
 {% block title %} FindIvest | supprimer un projet {% endblock %}

 {% block content %}

 <div style="margin: 10% 20%; height: 500px; width: 500px; position: relative;">
    <h2 class="text-center"> voulez vous vraiment suprimerz {{ projet_del }}</h2>
    <style type="text/css">
        .btn{
            margin-left: 50px;
        }

        #del{
            margin-left: 100px;
        }
    </style>
  <form action="{% url 'delete_post' projet_del.id %}" method="POST">
    {% csrf_token %}
    <input type="submit" id='del' class="btn btn-danger" value="delete">
    <a href="{% url 'accueil' %}" class="btn btn-primary">annuler</a>

  </form>
 </div>
 

 {% endblock %}

templates/posts/list_projects.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>List of projects</title>
    </head>
    <body>
        {% for post in postList %}
            titre : {{post.title}} <br>
            catégorie : {{post.categorie}} <br>
            doc : {{post.media}} <br>
            image : {{post.image}} <img width="300px" height="300px" src="{{post.image.url}}" alt="" srcset=""> <br>
            description : {{post.description}} <br><br>
            posté par : {{post.etudiant}}, nom : {{post.etudiant.user.last_name}} <br>
            <a href="{% url 'profile_student' post.etudiant.id %}">profile</a><br><br>
            posté le : {{post.date_post}} <br>
            investi : {{post.investi}} <br><br>

            <a href="{% url 'update_post' post.id %}">Modifier</a>
            <a href="{% url 'delete_post' post.id %}">Supprimer</a>

            <hr>
        {% endfor %}
    </body>
</html>

templates/posts/update_post.html
{% extends 'base-accueil.html' %}
{% load static %}

{% block title %} FindInvest | Modifier un projet {% endblock %}

{% block content %}

<style>
	#modifyPostModal{
		background: rgba(0, 0, 0, 0.5) !important;
	}
</style>

<div class="modal fade show" id="modifyPostModal" tabindex="-1" aria-labelledby="modifyPostLabel" style="display: block; padding-left: 0px;" aria-modal="true" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modifyPostLabel">Publier/Modifier un projet</h5>
          <i id="fermerMod" class="uil uil-multiply" data-bs-dismiss="modal" aria-label="Close" onclick="history.back()"></i>
        </div>
        <div class="modal-body">
            <style>
                textarea{
                    width: 100%;
                    height: 100px;
                }
            </style>
            
			{% comment %} <form id="create_form" method="post" enctype="multipart/form-data">
				{{projet_form}}

				<input type="text" id="form_type" name="form_type" value="create_form" hidden=""><p></p>
                <center><input class="mt-4 btn btn-primary" type="submit" value="Publier"></center>
			</form> {% endcomment %}

            <form id="create_form" method="post" enctype="multipart/form-data">
                <input type="hidden" name="csrfmiddlewaretoken" value="eHq97Vw4aREHzz2HyvRBI2l0yBMlVPto3imbgD5X5eXoyLm6w79vo2YTowwg1IN1"> 
                    
                    
                    {% comment %} <input type="text" name="title" maxlength="200" required="" id="id_title" placeholder="Titre du Projet"><p></p> {% endcomment %}
                    {{projet_form.title}} <p></p>

                    <p style="display: flex; align-items: center; gap: 1rem;">
                        <label for="id_categorie">Catégorie</label>
                        {% comment %} <select name="categorie" id="id_categorie">
							<option value="INFORMATIQUE">INFORMATIQUE</option>

							<option value="AGRICULTURE">AGRICULTURE</option>

							<option value="ELEVAGE">ELEVAGE</option>

							<option value="SANTE">SANTE</option>

							<option value="AUTRES">AUTRES</option>

						</select> {% endcomment %}
						{{projet_form.categorie}}
                    </p><p></p>

                    {% comment %} <select name="investi" id="id_investi" hidden="">
                        <option value="">---------</option>

                        <option value="Oui">Oui</option>

                        <option value="Non" selected="">Non</option>

                    </select> {% endcomment %}
					<span style="display: none;">
						{{projet_form.investi}}
					</span>

                    {% comment %} <textarea name="description" cols="40" rows="10" maxlength="500" required="" id="id_description" placeholder="Description"></textarea><p></p> {% endcomment %}
					{{projet_form.description}} <p></p>

                    {% comment %} <select name="etudiant" required="" id="id_etudiant" hidden="">
                        <option value="1">FindInvest_e Profile</option>
                    </select> {% endcomment %}
					<span style="display: none;">
						{{projet_form.etudiant}}
					</span>

                    <center>
                        <label id="image_post" for="id_image">
                            <span>Insérez une image</span>
                            <i class="uil uil-image-plus"></i>
                            <img id="upload_image" src="{{projet.image.url}}" alt="">
                        </label>
                    </center>
                    <input type="file" name="image" accept="image/*" id="id_image" hidden=""><p></p>
					<span>
						{% comment %} {{projet_form.image}} {% endcomment %}
					</span>
                    <hr>
                    <center>
                        <p class="mt-2 mb-0 text-small">Ajoutez un fichier qui décrire de manière plus détaillée votre projet</p>
                        <label id="media_post" for="id_media">
                            <i class="uil uil-file-plus"></i>
                            <span class="text-muted text-small" id="upload_file">{{projet.media}}</span>
                        </label>
                    </center>
                    <input type="file" name="media" id="id_media" hidden=""><p></p>


                    <input type="text" id="form_type" name="form_type" value="create_form" hidden=""><p></p>
                    <center><input class="mt-4 btn btn-primary" type="submit" value="Publier"></center>
                    
            </form>
        </div>
      </div>
    </div>
</div>


<!-- charger les ficheirs du formulaire de création d'un post -->
<script>
    // charger l'image

	let choosenImage = document.getElementById('upload_image');
	let uploardButton = document.getElementById('image_post');
    let postImage = document.getElementById('id_image');

	let ListExt = ["jpeg", "jpg", "png", "tif", "gif",
				   "JPEG", "JPG", "PNG", "TIF", "GIF"];
	postImage.onchange = () =>{
		let fileName = postImage.files[0].name.split(".");
		let ext = fileName[fileName.length-1];
		if(ListExt.indexOf(ext) === -1){
			alert("Veuillez sélectionner une image png, jpeg, jpg, tif ou gif");
		}else{
			let reader = new FileReader();
			reader.readAsDataURL(postImage.files[0]);
			let file = postImage.files[0];
			reader.onload = () => {
				choosenImage.setAttribute("src", reader.result);

			}
		}
	}

    // charger le nom de ficher

    nomFile = document.getElementById('upload_file');
    postFile = document.getElementById('id_media');

    postFile.onchange = () =>{
		let fileName = postFile.files[0].name;
		nomFile.innerHTML = fileName;
	}
</script>




<!-- ---------- copie de la page d'accueil --------------- -->

{% include "posts/accueil.html" %}



{% endblock %}