FindInvest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('reset_password', views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='reset_password'),
    path('reset_password_send', views.PasswordResetDoneView.as_view(template_name='registration/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password_complete', views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name="index"),
    path('accueil', accueil, name="accueil"),

    #  crud post
    path('delete_post/<str:pk>', delete_post, name='delete_post'),
    path('update_post/<str:pk>', update_post, name='update_post'),
    path('create_post', create_post, name='create_post'),
    path('list_projects', list_projects, name='list_projects'),
    path('mes_projets/<str:id_e>', mes_projets, name='mes_projets'),


    # chat 
    path('<str:room>/', room, name="room"),
    path('send', send, name='send'),
    path('getMessages/<str:room>/', getMessages, name='getMessages'),
    path('createRoom/<str:u1>/<str:u2>/<str:title>', createRoom, name='createRoom'),

    # comment post
    path('CommentPost', CommentPost, name='CommentPost'),
    path('getComments', getComments, name='getComments'),

    # favoris
    path('favoris/<str:id_u>', favoris, name="favoris"),
    path('createFavoris', createFavoris, name="createFavoris"),
    path('getFavoris', getFavoris, name='getFavoris'),

    # marquer investi
    path('markPost', markPost, name='markPost'),

]

users/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # connexion et déconnexion
    path('connexion', connexion, name="connexion"),
    path('déconnexion', user_logout, name="user_logout"),

    # réinitaliser mdp par question/reponse (non terminée)
    path('reset_password', reset_pwd, name="reset_pwd"),
    path('new_password', new_password, name="new_password"),

    # s'enregister et modfier son profil (étudiant et investisseur)
    path('register_student', register_student, name="register_student"),
    path('register_investor', register_investor, name="register_investor"),
    # path('update_profile/<str:id_e>', update_profile_student, name="update_profile_student"),
    path('update_profile', update_profile_student, name="update_profile_student"),
    path('profile_student/<str:id_e>', profile_student, name="profile_student"),
    # path('update_profile_i/<str:id_i>', update_profile_investor, name="update_profile_investor"),
    path('update_profile_i', update_profile_investor, name="update_profile_investor"),
    path('profile_investor/<str:id_i>', profile_investor, name="profile_investor"),

    # inscrition via github et google
    path('signup', signup, name='signup'),
    path('signup/student_register/<str:pk>',student_signup, name='student_signup'),
    path('signup/investor_register/<str:pk>', investor_signup, name='investor_signup'),
]

users/models.py
from django.db import models
from django.db.models.deletion import CASCADE, SET_NULL
from django.contrib.auth.models import User
import os

# Create your models here.

 

# creation la classe Utilisateur

class Utilisateur(models.Model):

    ville = models.CharField(max_length=100, null=True)
    telephone = models.CharField(max_length=100, null=True)
    photoProfil = models.ImageField(upload_to='image/profile_pics/', default='default.jpeg', blank=True)
    question = models.CharField(max_length=100)
    reponse = models.CharField(max_length=100)

    # pour que la classe ne crée pas une table dans la BD
    class Meta:
        abstract = True
    


# creation de la Classe Etudiant

class Etudiant(Utilisateur):
    # User possede déja : username, email, first_name, last_name, (password 1 et 2)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='etudiant')

    NIVEAUX = [
        ('BAC + 1', 'BAC + 1'),
        ('BAC + 2', 'BAC + 2'),
        ('BAC + 3', 'BAC + 3'),
        ('BAC + 4',  'BAC + 4'),
        ('BAC + 5', 'BAC + 5'),
        ('Doctorant', 'Doctorant'),
    ]
    niveauEtude = models.CharField(choices=NIVEAUX, default='BAC + 1', max_length=100)
    universite = models.CharField(max_length=100)
    fiche_inscription = models.FileField(upload_to='documents/fiches_inscription', blank=True)
    bio = models.TextField(max_length=300, null=True, blank=True, default="Je suis un étudiant de l'UNIVERSITÉ DE YAOUNDÉ 1. Je suis assez ambitieux et jai des projets que je souhaiterais mettre sur le marché.")
    def __str__(self):
        return f'{self.user.username} Profile'



# creation de la classe Investisseur

class Investisseur(Utilisateur):
    # User possede déja : username, email, first_name, last_name, (password 1 et 2)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='investisseur')

    profession = models.CharField(max_length=100)
    objectifs = models.CharField(max_length=300)
    entreprise = models.CharField(max_length=100, blank=True, default='Non renseigné')
    def __str__(self):
        return f'{self.user.username} Profile'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import fields
from .models import Etudiant, Investisseur


# formulaire pour DJANGO user
class UserForm(UserCreationForm):
    class Meta():
        model = User
        fields = [
            'username',
            'last_name',
            'email',
            'password1',
            'password2'
        ]
# formulaire pour modifier DJANGO user
class UserUpadateForm(forms.ModelForm):
    class Meta():
        model = User
        fields = [
            'username',
            'last_name',
            'email',
        ]
#  formulaire pour définir le nouveau password
class PwdUpdateForm(forms.ModelForm):
    class Meta():
        model = User
        fields = [
            'username',
            # 'password1',
            # 'password2'
        ]

# formulaire pour Etudiant
class EtuForm(forms.ModelForm):
    # Pour tout les champs tu doit definir sa correspondance en formfields
    # exemple
    # bio = forms.CharField(widget=forms.Textarea)

    class Meta():
        model = Etudiant
        fields = [
            'bio',
            'fiche_inscription',
            'universite',
            'niveauEtude',
            'reponse',
            'question',
            'photoProfil',
            'telephone',
            'ville'
        ]

    #  implemnter la methode save

    # def save(self, commit=True):
        

# formulaire pour Investisseur
class InvestForm(forms.ModelForm):
    class Meta():
        model = Investisseur
        fields = [
            'entreprise',
            'objectifs',
            'profession',
            'reponse',
            'question',
            'photoProfil',
            'telephone',
            'ville'
        ]

users/views.py
from distutils.command.sdist import sdist
from multiprocessing import context
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserForm, EtuForm, InvestForm, UserUpadateForm, PwdUpdateForm
from .models import Etudiant, Investisseur
from django.contrib.auth.models import User
from posts.models import Projet

# Create your views here.



# page de connexion

def connexion(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                if user.is_authenticated:
                    logout(request)
                login(request, user)
                return HttpResponseRedirect('../accueil')  
            else:
                return HttpResponse("L'utilisateur est désactivé")
        else:
            msg = messages.info(request, "votre Adresse mail ou votre Mot de passe est incorrect, veuillez réessayer !")
            context = {
                'msg':msg
            }
            return render(request, 'users/connexion.html', context)
    else:
        return render(request, 'users/connexion.html')



# reinitialiser mot de passe

def reset_pwd(request):
    err = ""
    question = ""
    rep = ""
    existe = False
    listEtu = []
    listInv = []
    for etu in Etudiant.objects.all():
        listEtu.append(etu.user.username)
    for inv in Investisseur.objects.all():
        listInv.append(inv.user.username)

    if request.method == 'POST':
        username = request.POST.get('username')
        methode = request.POST.get('methode')
        reponse = request.POST.get('reponse')

        # if methode == "1":
        
        for user in User.objects.all():
            if user.username == username:
                if username in listEtu:
                    question = user.etudiant.question
                    rep = user.etudiant.reponse
                elif username in listInv:
                    question = user.investisseur.question
                    rep = user.investisseur.reponse
                existe = True
                break

        if existe:
            if reponse == rep:
                return HttpResponseRedirect("new_password")
            else:
                err = messages.error(request, "Réponse incorrecte, Veuillez réessayer !")
            context = {
                'username':username,
                'question':question,
                'rep':rep,
                'existe':existe,
                'err':err
            }
            return render(request, 'users/reset_password.html', context)
        else:
            err = messages.error(request, "Il n'existe pas un utilisateur ayant cette adresse email. Veuillez réessayer !")
            context = {
                'err':err,
                'existe':existe
            }
            return render(request, 'users/reset_password.html', context)
    else:
        return render(request, 'users/reset_password.html')
       



# définir le nouveau mot de passe

def new_password(request):
    pwd_form = PwdUpdateForm()
    if request.method == 'POST':
        existe = False
        username = request.POST.get('username')
        for use in User.objects.all():
            if use.username == username:
                pwd_form = PwdUpdateForm(data=request.POST, instance=use)
                break

        # pwd_form = PwdUpdateForm(data=request.POST)
        
        if pwd_form.is_valid():

            # enregistrer dans la BD
            pwd = pwd_form.save()
            pwd.save()
            return HttpResponseRedirect("connexion")
            
    return render(request, 'users/new_password.html')





# se déconnecter
@login_required(login_url='connexion')
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


# page d'inscription des etudiants

def register_student(request):
    registered = False
    util = ""
    num_tel = ""
    err1 = ""
    err2 = ""
    user_form = UserForm()
    etu_form = EtuForm()

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        etu_form = EtuForm(data=request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password1')
        telephone = request.POST.get('telephone')
        if user_form.is_valid() and etu_form.is_valid():

            # enregistrer dans la BD
            user = user_form.save()
            user.save()
            etudiant = etu_form.save(commit=False)
            etudiant.user = user
            etudiant.save()
            registered = True
            
            # connecter le user
            user_log = authenticate(username=username, password=password)
            if user_log:
                if user.is_authenticated:
                    logout(request)
                login(request, user_log)
            # le renvoyer vers la page d'accueil 2
            return HttpResponseRedirect('../accueil')
        else:
            util = username
            num_tel = telephone
            err1 = user_form.errors
            err2 = etu_form.errors

    context = {
        'registered':registered,
        'user_form':user_form,
        'etu_form':etu_form,
        'util':util,
        'num_tel':num_tel,
        'err1':err1,
        'err2':err2,
    }
    return render(request, 'users/register_student.html', context)



# page d'incrition des investisseurs

def register_investor(request):
    registered = False
    util = ""
    num_tel = ""
    err1 = ""
    err2 = ""
    user_form = UserForm()
    invest_form = InvestForm()

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        invest_form = InvestForm(data=request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password1')
        telephone = request.POST.get('telephone')
        if user_form.is_valid() and invest_form.is_valid():

            # enregistrer dans la BD
            user = user_form.save()
            user.save()
            etudiant = invest_form.save(commit=False)
            etudiant.user = user
            etudiant.save()
            registered = True
            
            # connecter le user
            user_log = authenticate(username=username, password=password)
            if user_log:
                if user.is_authenticated:
                    logout(request)
                login(request, user_log)
            # le renvoyer vers la page d'accueil 2
            return HttpResponseRedirect('../accueil')
        else:
            util = username
            num_tel = telephone
            err1 = user_form.errors
            err2 = invest_form.errors

    context = {
        'registered':registered,
        'user_form':user_form,
        'invest_form':invest_form,
        'util':util,
        'num_tel':num_tel,
        'err1':err1,
        'err2':err2,
    }
    return render(request, 'users/register_investor.html', context)



# page modifier profil étudiant

@login_required(login_url='connexion')
def update_profile_student(request):
    err1 = ''
    err2 = ''
    etu_form = EtuForm(instance=request.user.etudiant)
    user_form = UserUpadateForm(instance=request.user)
    if request.method == "POST":
        etu_form = EtuForm(request.POST, request.FILES, instance=request.user.etudiant)
        user_form = UserUpadateForm(data=request.POST, instance=request.user)
        username = request.POST.get('username')
        password = request.POST.get('password1')
        
        if user_form.is_valid() and etu_form.is_valid():

            # enregistrer dans la BD
            user = user_form.save()
            user.save()
            etudiant = etu_form.save(commit=False)
            etudiant.user = user
            etudiant.save()
            
            # connecter le user
            user_log = authenticate(username=username, password=password)
            if user_log:
                if user.is_authenticated:
                    logout(request)
                login(request, user_log)
            # le renvoyer vers la page d'accueil 2
            return HttpResponseRedirect('../../../accueil')
        else:
            err1 = user_form.errors
            err2 = etu_form.errors

    context = {
        'user_form':user_form,
        'etu_form':etu_form,
        'err1':err1,
        'err2':err2,
    }
    return render(request, 'users/update_profile_student.html', context)



# page modifier profil investisseur

@login_required(login_url='connexion')
def update_profile_investor(request):
    err1 = ''
    err2 = ''

    # identifier un étudiant spécifique par son id
    # investisseur = Investisseur.objects.get(id=id_i)
    
    # identifier le user associé à cet investissuer, par son id
    # user = User.objects.get(id=investisseur.user.id)
    
    # remplir le formulaire avec les info de l'etudiant
    invest_form = InvestForm(instance=request.user.investisseur)
    user_form = UserUpadateForm(instance=request.user)
    if request.method == "POST":
        invest_form = InvestForm(request.POST, request.FILES, instance=request.user.investisseur)
        user_form = UserUpadateForm(data=request.POST, instance=request.user)
        username = request.POST.get('username')
        password = request.POST.get('password1')
        
        if user_form.is_valid() and invest_form.is_valid():

            # enregistrer dans la BD
            user = user_form.save()
            user.save()
            investisseur = invest_form.save(commit=False)
            investisseur.user = user
            investisseur.save()
            
            # connecter le user

templates/users/update_profile_investor.html
{% extends 'base.html' %}
{% load static %}

{% block title %} FindInvest | Update Profile {% endblock %}

{% block content %}

<style>
	body{
		margin-top:20px;
		background-color:#f2f6fc;
		color:#69707a;
	}
	.rounded-circle {
	    border-radius: 50% !important;
	}
	.card {
	    box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
	}
	.card .card-header {
	    font-weight: 500;
	}
	.card-header:first-child {
	    border-radius: 0.35rem 0.35rem 0 0;
	}
	.card-header {
	    padding: 1rem 1.35rem;
	    margin-bottom: 0;
	    background-color: rgba(33, 40, 50, 0.03);
	    border-bottom: 1px solid rgba(33, 40, 50, 0.125);
	}
	.form-control, .dataTable-input {
	    display: block;
	    width: 100%;
	    padding: 0.875rem 1.125rem;
	    font-size: 0.875rem;
	    font-weight: 400;
	    line-height: 1;
	    color: #69707a;
	    background-color: #fff;
	    background-clip: padding-box;
	    border: 1px solid #c5ccd6;
	    -webkit-appearance: none;
	    -moz-appearance: none;
	    appearance: none;
	    border-radius: 0.35rem;
	    transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
	}

	.nav-borders .nav-link.active {
	    color: #0b5ed7;
	    border-bottom-color: #0b5ed7;
	}
	.nav-borders .nav-link {
	    color: #69707a;
	    border-bottom-width: 0.125rem;
	    border-bottom-style: solid;
	    border-bottom-color: transparent;
	    padding-top: 0.5rem;
	    padding-bottom: 0.5rem;
	    padding-left: 0;
	    padding-right: 0;
	    margin-left: 1rem;
	    margin-right: 1rem;
	}

	.card{
		position: relative;
		border-top: #0b5ed7 solid 2px;
      	/* border-radius: 20px; */
		/* overflow: hidden; */
	}

	textarea{
		height: 64px !important;
	}
	select{
		height: 41px !important;
	}

	/*--------- button uploard profile picture -------------*/

	.pp{
		position: relative;
		width: 100%;
		margin-bottom: 15px;
	}

	.pp .profile_pp{
		position: relative;
		width: 10rem;
		height: 10rem;
		border-radius: 50%;
		overflow: hidden;
		margin: auto;
		/* border: #0b5ed7 dashed 0.5px; */
		box-shadow: 0 0 0.3rem #0b5ed7;
	}
	.profile_pp img{
		width: 100%;
	}

	#up_pp{
		position: absolute;
		top: 0rem;
		right: 0rem;
		z-index: 12;
	}
	.uil-pen{
		
		color: #0b5ed7;
		cursor: pointer;
		font-size: 25px;
		transition: 0.3s;
	}
	#up_pp:hover .uil-pen{
		color: #fff;
		background: #0b5ed7;
		border-radius: 50%;
		font-size: 20px;
		padding: 6px;
		transition: 0.3s;
	}

</style>

<div class="container px-4 mt-4">
<form name="formUpdateInv" onsubmit="return validateFormUpdateInv()" action="" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
    <nav class="nav nav-borders">
        <a class="nav-link ms-0" href="{% url 'accueil' %}">Accueil</a>
        <a class="nav-link active ms-0" href="{% url 'update_profile_investor' %}">Modifier profil</a>
    </nav>
    <hr class="mt-0 mb-4">
    <div class="row">
        <div class="col-md-4">
            <!-- Profile picture card-->
            <div class="card mb-4 mb-xl-0">
                <div class="card-header">Photo de profil</div>
					
                <div class="card-body text-center">
					<div class="pp">
						<label id="up_pp" for="id_photoProfil"><i class="uil uil-pen"></i></label>
						<div class="profile_pp">
							<img id="choosen-image" class="" src="{{request.user.investisseur.photoProfil.url}}" alt="">
						</div>
                    </div>
                    <div>
                    	<input type="file" name="photoProfil" accept="image/*" id="id_photoProfil" class="form-control" hidden>
                    </div>
                    <div class="small font-italic text-muted mb-4">{{request.user.username}}</div>
                    <!-- Profile picture upload button-->
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <!-- Account details card-->
            <div class="card mb-4">
                <div class="card-header">Détail du compte</div>
                <div class="card-body">
                    <!-- Form Row-->
                    <div class="row gx-3">
                        <!-- Form Group (first name)-->
                        <div class="col-md-12">
                            <label class="small mb-1" for="id_last_name">Noms et prénoms*</label>
                            {{user_form.last_name}}
							<p><span class="errorform" id="error_last_nameEtu"></span></p>                        </div>
                    </div>
                    <!-- Form Row        -->
                    <div class="row gx-3">
                        <!-- Niveau-->
                        <div class="col-md-6">
                            <label class="small mb-1" for="id_profession">Profession</label>
                            {{invest_form.profession}}
							<p><span class="errorform" id="error_professionInv"></span></p>
                        </div>

                        <!-- Université-->
                        <div class="col-md-6">
                            <label class="small mb-1" for="id_entreprise">Nom de l'entreprise</label>
                            {{invest_form.entreprise}}
							<p><span class="errorform" id="error_entrepriseInv"></span></p>
                        </div>
                    </div>
                    <div class="row gx-3">
                        <div class="col-md-6">
                            <label class="small mb-1" for="id_objectifs">Vos objectif sur la plateforme</label>
                            {{invest_form.objectifs}}
							<p><span class="errorform" id="error_objectifsInv"></span></p>
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1" for="id_ville">Ville</label>
							{{invest_form.ville}}
							<p><span class="errorform" id="error_villeEtu"></span></p>
                        </div>  
                        <div class="col-md-6">
                            <label class="small mb-1" for="id_telephone">Numéro de téléphone</label>
							{{invest_form.telephone}}
							<p><span class="errorform" id="error_telephoneEtu"></span></p>
                        </div>                    </div>
                    <div class="row gx-3">
                           
                    </div>
                </div>
            </div>

            <!-- Authrntification details card-->
            <div class="card mb-4">
                <div class="card-header">Information de connexion</div>
            	<div class="card-body">
                    <!-- Form Row-->
                    <div class="row gx-3">
                        <!-- Adresse mail-->
                        <div class="col-md-12">
                            <label class="small mb-1" for="Adresse">Adresse mail</label>
                            {% if user_form.username.errors %}
								<span class="errorform">Un utilisateur avec cette addresse existe déjà.</span>
							{% endif %}

							{{user_form.email}}
							<p><span class="errorform" id="error_emailEtu"></span></p>
                        </div>
                    </div>

                    <style>
						.form-group {
							position: relative;
						}
						.fom {
						  align-items: center !important;
						  display: flex;
						}
						.far {
						  position: absolute;
						  top: 15px;
						  right: 4%;
						  cursor: pointer;
						  color: rgb(48, 48, 48);
						  font-size: 20px;
						}
					</style>

					<div style="display: none;">
						{{user_form.username}}
					</div>

					<div class="row gx-3">
                        <!-- Question de sécurité-->
                        <div class="col-md-12">
                            <label class="small mb-1" for="id_question">Nouvelle question (à répondre en cas d'oublie de votre mot de passe*)</label>
							{{invest_form.question}}
							<p></p>
                        </div>
                        <!-- Réponse de sécurité-->
                        <div class="col-md-6">
                            <label class="small mb-1" for="id_reponse">Votre réponse </label>
							{{invest_form.reponse}}
							<p><span class="errorform" id="error_questionInv"></span></p>
                        </div>
                    </div>

                    <div class="row my-3">
                        <!-- Save changes button-->
                        <div class="col-sm-6 mt-3 offset-sm-3 text-center">
                            <input class="btn-bleu px-5" type="submit" value="Enregistrer">
                    	</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
</div>


<script>
	champsForm = document.getElementsByTagName('input');
	for (let i = 0; i < (champsForm.length-1); i++) {
		champsForm[i].classList.add('form-control');
		
	}
	selectChamps = document.getElementsByTagName('select');
	for (let i = 0; i < (selectChamps.length); i++) {
		selectChamps[i].classList.add('form-select');
	}
	textAeraChamps = document.getElementsByTagName('textarea');
	for (let i = 0; i < (selectChamps.length); i++) {
		textAeraChamps[i].classList.add('form-control');
	}

	window.addEventListener("keypress", function(event) {
		if (event.key === "Enter") {
			document.forms["formUpdateInv"].onsubmit();
		}
	});


	// valider le formulaire

	function validateFormUpdateInv(){
		// alert("recu");
		// return false;
		return true;
	}

	// charger l'image

	let choosenImage = document.getElementById('choosen-image');
	let uploardButton = document.getElementById('id_photoProfil');

	let ListExt = ["jpeg", "jpg", "png", "tif", "gif",
				   "JPEG", "JPG", "PNG", "TIF", "GIF"];

	uploardButton.onchange = () =>{
		let fileName = uploardButton.files[0].name.split(".");
		let ext = fileName[fileName.length-1];
		// alert(ext);
		if(ListExt.indexOf(ext) === -1){
			alert("Veuillez sélectionner une image png, jpeg, jpg, tif ou gif");
		}else{
			let reader = new FileReader();
			reader.readAsDataURL(uploardButton.files[0]);
			let file = uploardButton.files[0];
			reader.onload = () => {
				choosenImage.setAttribute("src", reader.result);

			}
		}
	}





    
</script>

{% endblock %}